### ISSUE TITLE
What rationale using "item" instead "at"?

### ISSUE THREAD

**Issue by MaxGraey** [tabatkins/proposal-item-method#2]
Advantages of `Array.p.at(idx)` for example:
- it shorter.
- it consistent with `charCodeAt` and `codePointAt` in `String` object.
- It consistent with other languages like C++ STL (array::at), Ruby, Smalltalk
- this name more element agnostic and could be generalize with similar method for strings for example (which operate with code points).
- not collide with `NodeList.p.item(idx)`

`arr.item(idx)` for indexing used only in Eiffel lang if I'm not mistaken.

**Comment by bakkot** [comment]
Presumably to match [the existing method in the DOM](https://github.com/tabatkins/proposal-item-method#dom-justifications), as it says in the readme.

**Comment by MaxGraey** [comment]
It's bad idea due to `NodeList.p.item(idx)` define only in range `[0, list.length - 1]` according to spec:
https://www.w3.org/TR/DOM-Level-3-Core/core.html#ID-536297177
but main goal of this proposal is allowing negatives indexes as well which not possible with `item` method in NodeList

**Comment by bakkot** [comment]
This is also [discussed in the readme](https://github.com/tabatkins/proposal-item-method#possible-dom-compat-issues).

**Comment by hax** [comment]
Another benefit may be matching the name of `lastItem` as current https://github.com/tc39/proposal-array-last proposal (maybe also `firstItem` as https://github.com/tc39/proposal-array-last/issues/27), though it seems we don't need `lastItem` if we could just use `item(-1)` 😂

**Comment by hax** [comment]
> * it consistent with `charCodeAt` and `codePointAt` in `String` object.

This is actually a problem, what `string.at(i)` should return?

- no `string.at`: weird because we have `array.at`
- `string.charAt(i)` weird because we already have `charAt` but no corresponding `codePointAt()`
- `String.fromCodePoints(string.codePointAt(i))`, this is actually what https://github.com/mathiasbynens/String.prototype.at propose! But weird if we have `array.at`, because now `string[i]`is not same as `string.at(i)`

**Comment by ljharb** [comment]
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt ?

**Comment by MaxGraey** [comment]
> Another benefit may be matching the name of lastItem as current https://github.com/tc39/proposal-array-last

I guess this proposal supersedes `lastItem` due to `.item(-1)` or `.at(-1)` shorter than `.lastItem()` which is only a special case. So I don’t think this is an important point.

**Comment by hax** [comment]
I think programmers will expect `x.at(i)` always same as `x[i]` (except supporting negative index), so I feel make `string.at(i)` return `string.codePointAt(i)` is not a good idea. And as https://github.com/mathiasbynens/String.prototype.at/issues/4#issuecomment-371270965 , `codePointAt` itself seems not very useful.

**Comment by tabatkins** [comment]
Yeah, the name is a vital part of this proposal, and is explained in the README.
